language: node_js
services:
  - docker
node_js:
  - "7"
before_install:
  - docker build -t sancho8/lab4 .
  - docker run -d --name lab4 sancho8/lab4
  - docker exec -t lab4 npm test
before_script:
  - npm install
script:
  - npm run jslint
  - npm test