language: node_js
services:
  - docker
node_js:
  - "7"
before_install:
  - docker build -t sancho8/lab4 .
  - docker run -p 4002:8080 sancho8/lab4 
before_script:
  - npm install
script:
  - npm run jslint
  - npm test